import React, { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Play } from 'lucide-react';
import { mockData } from '../data/mock';
import { Card, CardContent } from './ui/card';
import gradientBar from '../assets/femega-gradient-bar.svg';

const VideoShowcase = () => {
  const { successVideos } = mockData;
  const [currentIndex, setCurrentIndex] = useState(0);
  const [visibleThumbnailCount, setVisibleThumbnailCount] = useState(5);
  const [selectedVideoId, setSelectedVideoId] = useState(null);
  const [videoTitles, setVideoTitles] = useState({});

  const videos = successVideos.map((video) => ({
    ...video,
    title: videoTitles[video.id] || video.title
  }));
  const selectedVideo = videos.find((video) => video.id === selectedVideoId);

  useEffect(() => {
    const mobileViewport = window.matchMedia('(max-width: 767px)');
    const updateVisibleThumbnailCount = () => {
      setVisibleThumbnailCount(mobileViewport.matches ? 2 : 5);
    };

    updateVisibleThumbnailCount();
    mobileViewport.addEventListener('change', updateVisibleThumbnailCount);
    return () => mobileViewport.removeEventListener('change', updateVisibleThumbnailCount);
  }, []);

  useEffect(() => {
    const controller = new AbortController();

    Promise.all(successVideos.map(async (video) => {
      const videoUrl = `https://www.youtube.com/watch?v=${video.videoId}`;
      const metadataUrl = `https://noembed.com/embed?url=${encodeURIComponent(videoUrl)}`;

      try {
        const response = await fetch(metadataUrl, { signal: controller.signal });
        if (!response.ok) return null;

        const metadata = await response.json();
        return metadata.title ? [video.id, metadata.title] : null;
      } catch {
        return null;
      }
    })).then((entries) => {
      if (!controller.signal.aborted) {
        setVideoTitles(Object.fromEntries(entries.filter(Boolean)));
      }
    });

    return () => controller.abort();
  }, [successVideos]);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % successVideos.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + successVideos.length) % successVideos.length);
  };

  // Not every YouTube video has a maxresdefault thumbnail. When it doesn't
  // exist, YouTube still returns a 200 response but with a tiny 120x90 grey
  // placeholder image instead of a real thumbnail, so a regular onError
  // handler never fires. We detect that placeholder size on load and swap to
  // hqdefault (always generated by YouTube) instead.
  const handleThumbnailLoad = (event) => {
    const img = event.target;
    if (img.naturalWidth <= 120 && !img.dataset.fallbackApplied) {
      img.dataset.fallbackApplied = 'true';
      img.src = `https://img.youtube.com/vi/${img.dataset.videoId}/hqdefault.jpg`;
    }
  };

  const openVideo = (video) => {
    setSelectedVideoId(video.id);
  };

  const closeVideo = () => {
    setSelectedVideoId(null);
  };

  const maxThumbnailStart = Math.max(0, videos.length - visibleThumbnailCount);
  const thumbnailStart = Math.min(currentIndex, maxThumbnailStart);
  const totalThumbnailPages = maxThumbnailStart + 1;
  const activeThumbnailPage = thumbnailStart;
  const visibleVideos = videos.slice(thumbnailStart, thumbnailStart + visibleThumbnailCount);

  const goToThumbnailPage = (page) => {
    setCurrentIndex(Math.min(page, maxThumbnailStart));
  };

  return (
    <section id="casos-exito" className="pt-12 pb-24 bg-gray-900 relative overflow-hidden sm:py-24">
      {/* Background Pattern */}
      <div className="absolute inset-0" style={{ backgroundColor: '#000' }}>
        <div className="absolute inset-0" style={{ backgroundColor: '#000' }}></div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Casos de Éxito
          </h2>
          <img src={gradientBar} alt="" className="w-96 max-w-full h-auto mx-auto mb-4" />
          <p className="text-xl text-gray-300">
            Descubre cómo transformamos marcas en experiencias que conectan, inspiran y permanecen en la mente y el corazón de sus audiencias.
          </p>
        </div>

        {/* Video Carousel */}
        <div className="relative">
          {/* Main Video Display */}
          <div className="relative overflow-hidden rounded-3xl">
            <Card className="bg-gray-800 border-0 overflow-hidden">
              <CardContent className="p-0">
                <div className="relative group cursor-pointer aspect-video bg-black" onClick={() => openVideo(videos[currentIndex])}>
                  <img
                    src={videos[currentIndex].thumbnail}
                    alt={videos[currentIndex].title}
                    data-video-id={videos[currentIndex].videoId}
                    onLoad={handleThumbnailLoad}
                    className="w-full h-full object-contain transition-transform duration-500 group-hover:scale-105"
                  />
                  
                  {/* Overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent"></div>
                  
                  {/* Play Button */}
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-20 h-20 bg-orange-500 rounded-full flex items-center justify-center transition-all group-hover:scale-110 group-hover:bg-orange-600 shadow-2xl">
                      <Play className="text-white ml-1" size={32} fill="white" />
                    </div>
                  </div>

                </div>
              </CardContent>
            </Card>

            <div className="mt-6 px-6 md:px-8">
              <h3 className="text-2xl md:text-3xl font-bold text-white break-words text-center lg:text-left">
                {videos[currentIndex].title}
              </h3>
            </div>

            {/* Navigation Arrows */}
            <button
              onClick={prevSlide}
              className="nav-arrow-btn no-hover-motion absolute left-4 top-1/2 -translate-y-1/2 w-12 h-12 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center transition-all z-10"
            >
              <ChevronLeft className="text-white" size={24} />
            </button>
            <button
              onClick={nextSlide}
              className="nav-arrow-btn no-hover-motion absolute right-4 top-1/2 -translate-y-1/2 w-12 h-12 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center transition-all z-10"
            >
              <ChevronRight className="text-white" size={24} />
            </button>
          </div>

          {/* Thumbnail Navigation (shows up to 5 videos per page) */}
          {totalThumbnailPages > 1 && (
            <div className="relative mt-8">
              <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                {visibleVideos.map((video, localIndex) => {
                  const index = thumbnailStart + localIndex;
                  return (
                    <div
                      key={video.id}
                      onClick={() => { setCurrentIndex(index); openVideo(video); }}
                      onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                          event.preventDefault();
                          setCurrentIndex(index);
                          openVideo(video);
                        }
                      }}
                      role="button"
                      tabIndex={0}
                      aria-label={`Reproducir ${video.title}`}
                      className={`relative cursor-pointer rounded-lg overflow-hidden transition-all aspect-video ${
                        index === currentIndex
                          ? 'ring-4 ring-fuchsia-500 scale-105'
                          : 'opacity-60 hover:opacity-100'
                      }`}
                    >
                      <img
                        src={video.thumbnail}
                        alt={video.title}
                        data-video-id={video.videoId}
                        onLoad={handleThumbnailLoad}
                        className="w-full h-full object-contain bg-black"
                      />
                      <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
                        <Play className="text-white" size={20} />
                      </div>
                    </div>
                  );
                })}
              </div>

              <button
                onClick={prevSlide}
                aria-label="Ver video anterior en las miniaturas"
                className="nav-arrow-btn no-hover-motion absolute left-1 md:-left-5 top-1/2 -translate-y-1/2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/20 backdrop-blur-md transition-all md:h-12 md:w-12"
              >
                <ChevronLeft className="text-white" size={24} />
              </button>
              <button
                onClick={nextSlide}
                aria-label="Ver siguiente video en las miniaturas"
                className="nav-arrow-btn no-hover-motion absolute right-1 md:-right-5 top-1/2 -translate-y-1/2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/20 backdrop-blur-md transition-all md:h-12 md:w-12"
              >
                <ChevronRight className="text-white" size={24} />
              </button>
            </div>
          )}

          {totalThumbnailPages > 1 && (
            <div className="mt-5 flex justify-center gap-3" aria-label="Paginación de videos">
              {Array.from({ length: totalThumbnailPages }).map((_, page) => {
                const pageStart = page;
                const pageEnd = Math.min(pageStart + visibleThumbnailCount, videos.length);
                const isActivePage = page === activeThumbnailPage;

                return (
                  <button
                    key={page}
                    onClick={() => goToThumbnailPage(page)}
                    aria-label={`Ver videos ${pageStart + 1} al ${pageEnd}`}
                    aria-current={isActivePage ? 'page' : undefined}
                    className={`thumbnail-page-dot no-hover-motion h-3 w-3 rounded-full transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 focus-visible:ring-offset-2 focus-visible:ring-offset-black ${
                      isActivePage ? 'bg-fuchsia-500' : 'bg-white'
                    }`}
                  />
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Video Modal */}
      {selectedVideo && (
        <div
          className="fixed inset-0 bg-black/95 z-50 flex items-center justify-center p-4"
          onClick={closeVideo}
        >
          <div className="relative w-full max-w-5xl" onClick={(e) => e.stopPropagation()}>
            <button
              onClick={closeVideo}
              className="absolute -top-12 right-0 text-white hover:text-orange-500 text-4xl font-light"
            >
              ×
            </button>
            <div className="relative pt-[56.25%]">
              <iframe
                src={`https://www.youtube.com/embed/${selectedVideo.videoId}?autoplay=1`}
                title={selectedVideo.title}
                className="absolute inset-0 w-full h-full rounded-xl"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>
          </div>
        </div>
      )}
    </section>
  );
};

export default VideoShowcase;
